openapi: "3.0.1"

info:
  title: "Francis Wedding"
  version: "v1"

paths:
  /controllo-invitato:
    get:
      summary: Controllo invitato
      parameters:
        - in: query
          name: nome
          schema:
            type: string
          required: true
        - in: query
          name: cognome
          schema:
            type: string
          required: true
      responses:
        '200':
          description: invitato!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
        "500":
          description: "Internal Server Error"    
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
      x-amazon-apigateway-request-validator: "validate-all"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:${region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${region}:${account_id}:function:${lambda_controllo_invitato}/invocations"
  
  /conferma-presenza:
    post:
      summary: Invitato conferma presenza
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfermaPresenza'
      responses:
        '200':
          description: T'appoooo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
        "500":
          description: "Internal Server Error"    
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
      x-amazon-apigateway-request-validator: "validate-all"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:${region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${region}:${account_id}:function:${lambda_conferma_presenza}/invocations"
      
components:
  schemas:
    InternalServerError:
      title: "InternalServerError"
      type: object
      properties:
        response:
          type: string
      example: {
        "response": "Internal Server Error"
      }
    Empty:
      title: "Empty"
      type: "object"
    ControlloInvitato:
      type: object
      properties:
        nome:
          type: string
        cognome:
          type: string
    ConfermaPresenza:
      type: object
      properties:
        nome:
          type: string
        cognome:
          type: string
        id:
          type: string
        username:
          type: string
        intolleranze:
          type: boolean
        intolleranze_list:
          type: string
        email:
          type: string
        telefono:
          type: string
        forestiero:
          type: boolean
        

  responses:
    OptionsMethodSuccess:
      description: "200 response"
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: "string"
        Access-Control-Allow-Methods:
          schema:
            type: "string"
        Access-Control-Allow-Headers:
          schema:
            type: "string"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Empty"